INSERT INTO TASK (PRIORITY, DESCRIPTION, REQUIRED_ROLE)
VALUES (1, 'DESCRIPTION 1', 'ROLE1');
INSERT INTO TASK (PRIORITY, DESCRIPTION, REQUIRED_ROLE)
VALUES (1, 'DESCRIPTION 2', 'ROLE2');
INSERT INTO WORK_SCHEDULE (
    ID_USER,
    ID_TASK,
    WEEKDAY,
    START_TIME,
    END_TIME,
    SCHEDULE_START_DATE,
    SCHEDULE_END_DATE
  )
VALUES (
    1,
    1,
    3,
    '20:05:10',
    '21:10:20',
    '2021-10-25',
    '2021-11-10'
  );
INSERT INTO WORK_SCHEDULE (
    ID_USER,
    ID_TASK,
    WEEKDAY,
    START_TIME,
    END_TIME,
    SCHEDULE_START_DATE,
    SCHEDULE_END_DATE
  )
VALUES (
    4,
    2,
    2,
    '20:05:10',
    '21:10:20',
    '2021-05-25',
    '2021-10-28'
  );