DROP TABLE IF EXISTS TICKET;
CREATE TABLE IF NOT EXISTS TICKET (
  ID_TICKET INT NOT NULL,
  ID_USER INT NOT NULL,
  ID_FLIGHT INT NOT NULL,
  RESERVED_DATE INT NOT NULL,
  BOUGHT_DATE INT NOT NULL,
  PRICE INT NOT NULL,
  STATUS INT NOT NULL,
  PRIMARY KEY (ID_TICKET)
);
